/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufla.dcc.lanchonete.gui;

import br.ufla.dcc.lanchonete.modelo.*;
import br.ufla.dcc.lanchonete.servicos.GerenciadorPedidos;
import br.ufla.dcc.lanchonete.servicos.Pedido;
import br.ufla.dcc.lanchonete.util.Utilidades;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 * Classe que representa a Tela Principal, que é reponsável pelo cadastro e 
 * alteração de pedidos.
 * 
 * @author Fabricio, Matheus e Priscilla
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private final GerenciadorPedidos gerenciadorPedidos;
    private boolean pedidoAberto;
    private boolean alterandoPedido;
    private int contadorPedidos;
    private List<Pedido> pedidosBuscados;
    
    /**
     * Cria nova Tela Principal.
     */
    public TelaPrincipal() {
        this.gerenciadorPedidos = new GerenciadorPedidos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lbPesquisarPedido = new javax.swing.JLabel();
        pnNovoPedido = new javax.swing.JLayeredPane();
        btnAdicionarBebidas = new javax.swing.JButton();
        btnRemoverUltimoItem = new javax.swing.JButton();
        lbCliente = new javax.swing.JLabel();
        btnFecharPedido = new javax.swing.JButton();
        tfCliente = new javax.swing.JTextField();
        lbBebidas = new javax.swing.JLabel();
        cbLanches = new javax.swing.JComboBox<>();
        lbLanches = new javax.swing.JLabel();
        btnAdicionarLanche = new javax.swing.JButton();
        cbBebidas = new javax.swing.JComboBox<>();
        cbQuantidadeLanches = new javax.swing.JComboBox<>();
        cbQuantidadeBebidas = new javax.swing.JComboBox<>();
        btnAbrirPedido = new javax.swing.JButton();
        pnListadePedidos = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPedidos = new javax.swing.JList<>();
        btnRemoverPedido = new javax.swing.JButton();
        btnAlterarPedido = new javax.swing.JButton();
        pnDetalhes = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDetalhes = new javax.swing.JTextArea();
        tfBuscarPedido = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbPesquisarPedido.setText("Buscar pedido (pelo nome do cliente)");

        pnNovoPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Novo pedido"));

        btnAdicionarBebidas.setText("Adicionar");
        btnAdicionarBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarBebidasActionPerformed(evt);
            }
        });

        btnRemoverUltimoItem.setText("Remover último item");
        btnRemoverUltimoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverUltimoItemActionPerformed(evt);
            }
        });

        lbCliente.setText("Cliente");

        btnFecharPedido.setText("Fechar pedido");
        btnFecharPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharPedidoActionPerformed(evt);
            }
        });

        lbBebidas.setText("Bebidas");

        cbLanches.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X-Bacon", "X-Egg", "X-Frango", "X-Salada", "X-Tudo" }));

        lbLanches.setText("Lanches");

        btnAdicionarLanche.setText("Adicionar");
        btnAdicionarLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarLancheActionPerformed(evt);
            }
        });

        cbBebidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Água", "Cerveja", "Refrigerante", "Suco" }));

        cbQuantidadeLanches.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        cbQuantidadeBebidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        btnAbrirPedido.setText("Abrir pedido");
        btnAbrirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirPedidoActionPerformed(evt);
            }
        });

        pnNovoPedido.setLayer(btnAdicionarBebidas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnNovoPedido.setLayer(btnRemoverUltimoItem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnNovoPedido.setLayer(lbCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnNovoPedido.setLayer(btnFecharPedido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnNovoPedido.setLayer(tfCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnNovoPedido.setLayer(lbBebidas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnNovoPedido.setLayer(cbLanches, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnNovoPedido.setLayer(lbLanches, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnNovoPedido.setLayer(btnAdicionarLanche, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnNovoPedido.setLayer(cbBebidas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnNovoPedido.setLayer(cbQuantidadeLanches, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnNovoPedido.setLayer(cbQuantidadeBebidas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnNovoPedido.setLayer(btnAbrirPedido, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnNovoPedidoLayout = new javax.swing.GroupLayout(pnNovoPedido);
        pnNovoPedido.setLayout(pnNovoPedidoLayout);
        pnNovoPedidoLayout.setHorizontalGroup(
            pnNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNovoPedidoLayout.createSequentialGroup()
                .addGroup(pnNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNovoPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNovoPedidoLayout.createSequentialGroup()
                                .addComponent(lbCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAbrirPedido))
                            .addComponent(lbBebidas)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNovoPedidoLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnRemoverUltimoItem)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(btnFecharPedido)
                                .addGap(30, 30, 30))))
                    .addGroup(pnNovoPedidoLayout.createSequentialGroup()
                        .addGroup(pnNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbLanches, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbBebidas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnNovoPedidoLayout.createSequentialGroup()
                                .addComponent(cbQuantidadeBebidas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdicionarBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnNovoPedidoLayout.createSequentialGroup()
                                .addComponent(cbQuantidadeLanches, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdicionarLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(pnNovoPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLanches)
                .addContainerGap(318, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnNovoPedidoLayout.setVerticalGroup(
            pnNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNovoPedidoLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(pnNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCliente)
                    .addComponent(btnAbrirPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbLanches)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLanches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarLanche)
                    .addComponent(cbQuantidadeLanches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbBebidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarBebidas)
                    .addComponent(cbQuantidadeBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoverUltimoItem)
                    .addComponent(btnFecharPedido))
                .addGap(12, 12, 12))
        );

        pnListadePedidos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Lista de pedidos"));

        lstPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPedidosMouseClicked(evt);
            }
        });
        lstPedidos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPedidosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPedidos);

        btnRemoverPedido.setText("Remover");
        btnRemoverPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverPedidoActionPerformed(evt);
            }
        });

        btnAlterarPedido.setText("Alterar");
        btnAlterarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPedidoActionPerformed(evt);
            }
        });

        pnListadePedidos.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnListadePedidos.setLayer(btnRemoverPedido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnListadePedidos.setLayer(btnAlterarPedido, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnListadePedidosLayout = new javax.swing.GroupLayout(pnListadePedidos);
        pnListadePedidos.setLayout(pnListadePedidosLayout);
        pnListadePedidosLayout.setHorizontalGroup(
            pnListadePedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListadePedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnListadePedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addGroup(pnListadePedidosLayout.createSequentialGroup()
                        .addComponent(btnAlterarPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoverPedido)))
                .addContainerGap())
        );
        pnListadePedidosLayout.setVerticalGroup(
            pnListadePedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListadePedidosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnListadePedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarPedido)
                    .addComponent(btnRemoverPedido))
                .addGap(41, 41, 41))
        );

        pnDetalhes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Detalhes do pedido"));

        taDetalhes.setEditable(false);
        taDetalhes.setColumns(20);
        taDetalhes.setRows(5);
        jScrollPane2.setViewportView(taDetalhes);

        pnDetalhes.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnDetalhesLayout = new javax.swing.GroupLayout(pnDetalhes);
        pnDetalhes.setLayout(pnDetalhesLayout);
        pnDetalhesLayout.setHorizontalGroup(
            pnDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetalhesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        pnDetalhesLayout.setVerticalGroup(
            pnDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetalhesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        tfBuscarPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfBuscarPedidoKeyTyped(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbPesquisarPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnNovoPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnListadePedidos))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnDetalhes)))
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfBuscarPedido)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPesquisarPedido))
                .addGap(5, 5, 5)
                .addComponent(tfBuscarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnNovoPedido)
                    .addComponent(pnListadePedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 252, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnDetalhes)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    //**********EVENTOS**********//
    
    /**
     * Evento do botão 'Remover pedido'.
     * 
     * @param evt 
     */
    private void btnRemoverPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverPedidoActionPerformed
        if (pedidoAberto || alterandoPedido) {
            Utilidades.msgInformacao("Feche o pedido atual para poder remover");
        } else {
            if (!lstPedidos.isSelectionEmpty()) {
                taDetalhes.setText("");
                gerenciadorPedidos.getListaPedidos().remove(lstPedidos.getSelectedIndex());
                modelTodos.remove(lstPedidos.getSelectedIndex());
                lstPedidos.setModel(modelTodos);
            } else {
                Utilidades.msgInformacao("Nenhum pedido selecionado");
            }
        }
    }//GEN-LAST:event_btnRemoverPedidoActionPerformed
    
    /**
     * Evento do botão 'Fechar Pedido'.
     * 
     * @param evt 
     */
    private void btnFecharPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharPedidoActionPerformed
        if (pedidoAberto || alterandoPedido) {
            pedidoAberto = false;
            alterandoPedido = false;
            Utilidades.msgInformacao("Pedido fechado!");
        } else {
            Utilidades.msgInformacao("Nenhum pedido aberto ou sendo alterado");
        }
    }//GEN-LAST:event_btnFecharPedidoActionPerformed
    
    /**
     * Evento do botão 'Adicionar', que adiciona o lanche e a quantidade selecionada ao pedido.
     * 
     * @param evt 
     */
    private void btnAdicionarLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarLancheActionPerformed
        if (pedidoAberto) {
            for (int i=0; i<5; i++) {
                if(cbLanches.getSelectedIndex()==i) {
                    for (int j=0; j<=cbQuantidadeLanches.getSelectedIndex(); j++) {
                        gerenciadorPedidos.getListaPedidos().get(gerenciadorPedidos.getListaPedidos().size()-1).addProduto(gerenciadorPedidos.getListaLanches().get(i));
                    }
                }
            }
        } else if (alterandoPedido) {
            for (int i=0; i<5; i++) {
                if(cbBebidas.getSelectedIndex()==i) {
                    for (int j=0; j<=cbQuantidadeLanches.getSelectedIndex(); j++) {
                        gerenciadorPedidos.getListaPedidos().get(lstPedidos.getSelectedIndex()).addProduto(gerenciadorPedidos.getListaLanches().get(i));
                    }
                }
            }
        } else {
            Utilidades.msgInformacao("Nenhum pedido aberto ou sendo alterado");
        }
    }//GEN-LAST:event_btnAdicionarLancheActionPerformed

    DefaultListModel modelTodos = new DefaultListModel(); //definindo um "modelo" para exibição da lista de todos os pedidos
    /**
     * Evento do botão 'Abrir pedido'.
     * 
     * @param evt 
     */
    private void btnAbrirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirPedidoActionPerformed
        if (!pedidoAberto && !alterandoPedido) {
            if (tfCliente.getText().length() > 0) {
                gerenciadorPedidos.abrirPedido(carregarPedido());
                modelTodos.addElement("Pedido " + gerenciadorPedidos.getListaPedidos().get(gerenciadorPedidos.getListaPedidos().size()-1).getNumeroPedido() + 
                                      " - " + gerenciadorPedidos.getListaPedidos().get(gerenciadorPedidos.getListaPedidos().size()-1).getCliente());
                lstPedidos.setModel(modelTodos);
                pedidoAberto = true;
                Utilidades.msgInformacao("             Pedido aberto!\nAdicione os produtos do pedido");
            } else {
                Utilidades.msgInformacao("Digite o nome do cliente");
            } 
        } else {
            Utilidades.msgInformacao("Feche o pedido atual antes de abrir outro");
        }
    }//GEN-LAST:event_btnAbrirPedidoActionPerformed
    
    /**
     * Evento do botão 'Sair', que fecha a tela princial.
     * 
     * @param evt 
     */
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed
    
    /**
     * Evento do botão 'Adicionar', que a adiciona a bebida e quantidade selecionada ao pedido.
     * @param evt 
     */
    private void btnAdicionarBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarBebidasActionPerformed
        if (pedidoAberto) {
            for (int i=0; i<4; i++) {
                if(cbBebidas.getSelectedIndex()==i) {
                    for (int j=0; j<=cbQuantidadeBebidas.getSelectedIndex(); j++) {
                        gerenciadorPedidos.getListaPedidos().get(gerenciadorPedidos.getListaPedidos().size()-1).addProduto(gerenciadorPedidos.getListaBebidas().get(i));
                    }
                }
            }
        } else if (alterandoPedido) {
            for (int i=0; i<4; i++) {
                if(cbBebidas.getSelectedIndex()==i) {
                    for (int j=0; j<=cbQuantidadeBebidas.getSelectedIndex(); j++) {
                        gerenciadorPedidos.getListaPedidos().get(lstPedidos.getSelectedIndex()).addProduto(gerenciadorPedidos.getListaBebidas().get(i));
                    }
                }
            }
        } else {
            Utilidades.msgInformacao("Nenhum pedido aberto ou sendo alterado");
        }
    }//GEN-LAST:event_btnAdicionarBebidasActionPerformed
    /**
     * Evento para mudança de dados exibidos na lista de pedidos.
     * 
     * @param evt 
     */
    private void lstPedidosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPedidosValueChanged
        try {
            if (tfBuscarPedido.getText().length() < 2) {
                atualizarDetalhes(gerenciadorPedidos.getListaPedidos().get(lstPedidos.getSelectedIndex()));
            } else {
                atualizarDetalhes(pedidosBuscados.get(lstPedidos.getSelectedIndex()));
            }
        } catch(ArrayIndexOutOfBoundsException e) { }
    }//GEN-LAST:event_lstPedidosValueChanged

    /**
     * Evento de busca de pedido.
     * 
     * @param evt 
     */
    private void tfBuscarPedidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarPedidoKeyTyped
        DefaultListModel modelBuscados = new DefaultListModel(); //definindo um "modelo" para exibição da lista apenas dos pedidos buscados
        pedidosBuscados = gerenciadorPedidos.buscarPedidos(tfBuscarPedido.getText());
        for (Pedido pedido : pedidosBuscados) {
            modelBuscados.addElement("Pedido " + pedido.getNumeroPedido() + " - " + pedido.getCliente());
        }
        lstPedidos.setModel(modelBuscados);
    }//GEN-LAST:event_tfBuscarPedidoKeyTyped

    /**
     * Evento do botão 'Remover ultimo item', que remove ultimo item adicionado ao pedido.
     * 
     * @param evt 
     */
    private void btnRemoverUltimoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverUltimoItemActionPerformed
        if (pedidoAberto) {
            if (gerenciadorPedidos.getListaPedidos().get(gerenciadorPedidos.getListaPedidos().size()-1).getProdutos().size() > 0) { 
                gerenciadorPedidos.getListaPedidos().get(gerenciadorPedidos.getListaPedidos().size()-1).removerUltimoProduto();
            } else {
                Utilidades.msgInformacao("Não há mais produtos no pedido");
            }          
        } else if (alterandoPedido) {
            if (gerenciadorPedidos.getListaPedidos().get(lstPedidos.getSelectedIndex()).getProdutos().size() > 0) {
                gerenciadorPedidos.getListaPedidos().get(lstPedidos.getSelectedIndex()).removerUltimoProduto();
            } else {
                Utilidades.msgInformacao("Não há mais produtos no pedido");
            } 
        } else {
            Utilidades.msgInformacao("Nenhum pedido aberto ou sendo alterado");
        }
    }//GEN-LAST:event_btnRemoverUltimoItemActionPerformed

    /**
     * Evento criado ao clicar em algum pedido da 'Lista de pedidos'.
     * 
     * @param evt 
     */
    private void lstPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPedidosMouseClicked
        try {
            if (tfBuscarPedido.getText().length() < 2) {
                atualizarDetalhes(gerenciadorPedidos.getListaPedidos().get(lstPedidos.getSelectedIndex()));
            } else {
                atualizarDetalhes(pedidosBuscados.get(lstPedidos.getSelectedIndex()));
            }   
        } catch(ArrayIndexOutOfBoundsException e) { }
    }//GEN-LAST:event_lstPedidosMouseClicked

    /**
     * Evento do botão 'Alterar pedido'.
     * 
     * @param evt 
     */
    private void btnAlterarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPedidoActionPerformed
        if (!lstPedidos.isSelectionEmpty()) {
            if (!pedidoAberto) {
                alterandoPedido = true;
            } else {
                Utilidades.msgInformacao("Feche o pedido atual antes de alterar o selecionado");
            }
        } else {
            Utilidades.msgInformacao("Nenhum pedido selecionado");
        }
    }//GEN-LAST:event_btnAlterarPedidoActionPerformed
 
   
    //**********MÉTODOS**********//
    
    /**
     * Inicia uma nova tela principal.
     */
    public void inicializar() {
        new TelaPrincipal().setVisible(true);
    }
    
    /**
     * Retorna um novo pedido a aprtir do nome do cliente e  número do pedido passados
     * .
     * @return Pedido criado.
     */
    private Pedido carregarPedido() {
        contadorPedidos++;
        return new Pedido(tfCliente.getText(), contadorPedidos, new ArrayList<>());
    } 
    
    /**
     * Atualiza a área de detalhes com os dados do pedido.
     * @param ped Pedido selecionado.
     */
    private void atualizarDetalhes(Pedido ped) {
        taDetalhes.setText("");
        taDetalhes.append("Número do pedido: " + ped.getNumeroPedido() + "\n");
        taDetalhes.append("Cliente: " + ped.getCliente() + "\n");
        taDetalhes.append("Preço total: R$" + ped.getPrecoTotal() + "\n");
        taDetalhes.append("\nProdutos:");
        for (Produto produto : ped.getProdutos()) {
            taDetalhes.append("\n" + produto.getNome() + " (" + produto.getDetalhes() + ") - R$" + produto.getPreco());
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirPedido;
    private javax.swing.JButton btnAdicionarBebidas;
    private javax.swing.JButton btnAdicionarLanche;
    private javax.swing.JButton btnAlterarPedido;
    private javax.swing.JButton btnFecharPedido;
    private javax.swing.JButton btnRemoverPedido;
    private javax.swing.JButton btnRemoverUltimoItem;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbBebidas;
    private javax.swing.JComboBox<String> cbLanches;
    private javax.swing.JComboBox<String> cbQuantidadeBebidas;
    private javax.swing.JComboBox<String> cbQuantidadeLanches;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbBebidas;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbLanches;
    private javax.swing.JLabel lbPesquisarPedido;
    private javax.swing.JList<String> lstPedidos;
    private javax.swing.JLayeredPane pnDetalhes;
    private javax.swing.JLayeredPane pnListadePedidos;
    private javax.swing.JLayeredPane pnNovoPedido;
    private javax.swing.JTextArea taDetalhes;
    private javax.swing.JTextField tfBuscarPedido;
    private javax.swing.JTextField tfCliente;
    // End of variables declaration//GEN-END:variables

}
